# Generated by Django 4.1 on 2022-09-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_text_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
